<?php declare(strict_types=1);

require_once 'helper/FormhandlerTestCase.php';

final class ConstructorTest extends FormhandlerTestCase
{
    final protected function getFormhandlerType() : string
    {
        return "Formhandler";
    } 
    public function testStandardFormname_POST() : void
    {
        $form = new FormHandler();

        $this->assertEquals(FH_DEFAULT_FORM_NAME, $form->getFormName());
        $this->assertFalse($form->isPosted());

        $this->assertEquals(1, $form->getCurrentPage());
        $this->assertEquals(1, $form->getLastSubmittedPage());
        $this->assertEquals(1, $form->getPage());
        $this->assertEquals(FH_DEFAULT_LANGUAGE, $form->getLang());
        $this->assertEquals(FH_DEFAULT_LANGUAGE, $form->getLanguage());
        $this->assertEmpty($form->getJavascriptCode());
        $this->assertTrue($form->isCorrect());
        $this->assertFalse($form->isViewMode());

        $html = $form->flush(true);
        $this->assertStringContainsString('<form id="' . FH_DEFAULT_FORM_NAME . '" method="post" action="', $html);
        $this->assertStringContainsString('<ins><input type="hidden" name="FormHandler_submit" id="FormHandler_submit" value="1" />', $html);
        $this->assertStringContainsString("</ins><table border='0' cellspacing='0' cellpadding='3' >", $html);
        $this->assertStringContainsString("<p><span style='font-family:tahoma;font-size:10px;color:#B5B5B5;font-weight:normal;'>This form is generated by </span><a href=\"http://www.formhandler.net\" ><span style=\"font-family:Tahoma;font-size:10px;color:#B5B5B5;\"><strong>FormHandler</strong></span></a></p>", $html);
    }

    public function testDeviantFormname_POST() : void
    {
        $form = new FormHandler("DeviantFormName");

        $this->assertEquals("DeviantFormName", $form->getFormName());
        $this->assertStringContainsString('<form id="DeviantFormName" method="post" action="', $form->flush(true));
    }

    public function testStandardFormname_POST_submit() : void
    {
        $_POST['FormHandler_submit'] = "1";

        $form = new FormHandler();

        $this->assertTrue($form->isPosted());
        $this->assertTrue($form->isCorrect());

        $this->assertEquals("", $form->flush(true));
    }

    public function testNoExpose() : void
    {
        define('FH_EXPOSE', false);

        $form = new FormHandler();

        $html = $form->flush(true);
        $this->assertStringContainsString('<form id="' . FH_DEFAULT_FORM_NAME . '" method="post" action="', $html);
        $this->assertStringContainsString('<ins><input type="hidden" name="FormHandler_submit" id="FormHandler_submit" value="1" />', $html);
        $this->assertStringContainsString("</ins><table border='0' cellspacing='0' cellpadding='3' >", $html);
        $this->assertStringNotContainsString("<p><span style='font-family:tahoma;font-size:10px;color:#B5B5B5;font-weight:normal;'>This form is generated by </span><a href=\"http://www.formhandler.net\" ><span style=\"font-family:Tahoma;font-size:10px;color:#B5B5B5;\"><strong>FormHandler</strong></span></a></p>", $html);
    }

    public function testTableWith100() : void
    {
        define('FH_DEFAULT_TABLE_WIDTH', 100);

        $form = new FormHandler();

        $html = $form->flush(true);
        $this->assertStringContainsString("</ins><table border='0' cellspacing='0' cellpadding='3' width='100' >", $html);
    }

    public function testTableBorder1() : void
    {
        define('FH_DEFAULT_TABLE_BORDER', 1);

        $form = new FormHandler();

        $html = $form->flush(true);
        $this->assertStringContainsString("</ins><table border='1' cellspacing='0' cellpadding='3' >", $html);
    }

    public function testTableCellspacing1() : void
    {
        define('FH_DEFAULT_TABLE_CELLSPACING', 1);

        $form = new FormHandler();

        $html = $form->flush(true);
        $this->assertStringContainsString("</ins><table border='0' cellspacing='1' cellpadding='3' >", $html);
    }

    public function testTableCellpadding1() : void
    {
        define('FH_DEFAULT_TABLE_CELLPADDING', 1);

        $form = new FormHandler();

        $html = $form->flush(true);
        $this->assertStringContainsString("</ins><table border='0' cellspacing='0' cellpadding='1' >", $html);
    }

    public function testNoField() : void
    {
        $form = new FormHandler();

        $this->expectError();
        //$this->expectErrorMessage('Try to get the value of an unknown field "notexist"!');

        $form->getValue("notexist");
    }
}